# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Basic site info
title:              "Dennis Czombera"
description:        "random_thoughts |> sprinkle_magic |> create_blog_post"
keywords:           "dennis czombera, personal blog, software developer, backend developer, ruby, ruby on rails, elixir, phoenix"
logo_text:          "Dennis Czombera"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              "/assets/logo.png" # site image cover

# Site URL settings
url:                http://dennisczombera.com # main url
baseurl:            null # for gh-pages
enforce_ssl:        dennisczombera.com

# Site author info
author:
  name:             "Dennis Czombera"
  email:            milchschaumschluerfer@gmail.com
  github_username:  dczombera 
  twitter_username: dczombera 

# Disqus comment settings
disqus_enabled:     true 
disqus_shortname:   dennisczombera-com 

# GA
google_analytics_code: UA-97573538-1 

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           Europe/Berlin
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md", "Gemfile", "Gemfile.lock"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

gems:
  - jekyll-sitemap
  - jekyll-feed
